#include "images.h"

const ext_img_desc_t images[30] = {
    { "tree", &img_tree },
    { "humadity", &img_humadity },
    { "visual", &img_visual },
    { "power", &img_power },
    { "temp", &img_temp },
    { "tool", &img_tool },
    { "fan", &img_fan },
    { "co2", &img_co2 },
    { "timer", &img_timer },
    { "backtemp", &img_backtemp },
    { "dec", &img_dec },
    { "inc", &img_inc },
    { "backfan", &img_backfan },
    { "visual_settings", &img_visual_settings },
    { "clock", &img_clock },
    { "timer_menu", &img_timer_menu },
    { "configuration", &img_configuration },
    { "tems", &img_tems },
    { "dispetcher", &img_dispetcher },
    { "grafik", &img_grafik },
    { "menu_out", &img_menu_out },
    { "tool_menu", &img_tool_menu },
    { "calendar", &img_calendar },
    { "clock_out", &img_clock_out },
    { "change_time", &img_change_time },
    { "temp_timer", &img_temp_timer },
    { "fan_timer", &img_fan_timer },
    { "start_timer", &img_start_timer },
    { "fann_timer", &img_fann_timer },
    { "backspace", &img_backspace },
};
