#include "images.h"

const ext_img_desc_t images[27] = {
    { "WiFi", &img_wi_fi },
    { "Brightness", &img_brightness },
    { "up", &img_up },
    { "down", &img_down },
    { "left", &img_left },
    { "right", &img_right },
    { "power", &img_power },
    { "tools", &img_tools },
    { "clock", &img_clock },
    { "Sound", &img_sound },
    { "Language", &img_language },
    { "Window", &img_window },
    { "Tree", &img_tree },
    { "Temp", &img_temp },
    { "Fan", &img_fan },
    { "timer", &img_timer },
    { "humadity", &img_humadity },
    { "Co2", &img_co2 },
    { "back", &img_back },
    { "Configuration", &img_configuration },
    { "Menu_tool", &img_menu_tool },
    { "timer60px", &img_timer60px },
    { "tree60px", &img_tree60px },
    { "Grafik", &img_grafik },
    { "dispetcher", &img_dispetcher },
    { "tems", &img_tems },
    { "visual", &img_visual },
};
